name: 'path-watcher-action'
description: 'check whether the head commit involved a change in one of the input paths'
inputs:
  github_token:
    description: 'github token'
  paths:
    description: 'comma separated list of paths'
    required: true
  return_files:
    description: 'if true, ouput will contain an array with the changed paths"
    required: false
    default: false
outputs:
  modified:
    description: 'whether the commit involves a change in any of the input paths'
  modified_files:
    description: 'array with the modified paths in the commit'
branding:
  icon: 'zoom-in'
  color: 'purple'
runs:
  using: 'node12'
  main: 'index.js'
